name: Deployment to GH Pages
on:
  push:
    branches: [ master ]
env:
  GITHUB_TOKEN: ${{ secrets.GIT_LINUX }}
  CI: true
  NEXT_TELEMETRY_DISABLED: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Setup Environment
      run: |
        npm install
    - name: Generate meta and builld
      run: |
        npm run meta
        npm run build
    - name: Deploy to GH Pages
      run: |
        git config user.email "pfp@live.com"
        git config user.name "Dongshanpi"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/DongshanPI/developer-linux.git
        npm run deploy
